mqtt:
    host: "blackbox-ubuntu-server16"
    port: 1883
    clientid: "default-pi" #this will also be the node id
    user: "homeassistant"
    password: "homeassistant"
    discovery_prefix: "homeassistant" #<discovery_prefix>/<component>/[<node_id>/]<object_id>/<>
system:
    sbctype: rpizero #not sure if this is needed, (in the future maybe this will be handles with platform options)
binary_sensors: #using HASS component terminology, binary_sensors, sensors, switches --> <discovery_prefix>/<component>/[<node_id>/]<object_id>/<>
    -   objectid:  "input1"
        iotype: "automationphat-input1"
        friendlyname: ""
        unit_of_measurement: ""
    -   objectid:  "input2"
        iotype: ""
    -   objectid:  "input3"
        iotype: ""
sensors: 
    -   objectid:  "analog1"
        iotype: ""
    -   objectid:  "analog2"
        iotype: ""
    -   objectid:  "analog3"
        iotype: ""
switches:
    -   objectid:  "relay1"
        iotype: ""
    -   objectid:  "output1"
        iotype: ""
    -   objectid:  "output2"
        iotype: ""
    -   objectid:  "output3"
        iotype: ""